# Change these first
owner: TheHardDiamond # Your GitHub organization or username, where this repository lives
repo: learning_server_check # The name of this repository

sites:
  - name: CSU-MC skin
    url: https://csu-mc.magicalsheep.cn
    icon: https://csu-mc.magicalsheep.cn/app/favicon.ico
  - name: CSU-MC yggdrasil
    url: https://csu-mc.magicalsheep.cn/api/yggdrasil
    icon: https://csu-mc.magicalsheep.cn/favicon.ico
  - name: CSU-MC Server Map
    url: https://map.magicalsheep.cn
    icon: https://map.magicalsheep.cn/favicon.ico
  - name: CSU-MC Server Home Page
    url: https://www.csu-mc.magicalsheep.cn/
    icon: https://www.csu-mc.magicalsheep.cn/imgs/minecraft_title.png
  #- name: Test Broken Site
  #  url: https://thissitedoesnotexist.koj.co
  #- name: IPv6 test
  #  url: forwardemail.net
  #  port: 80
  #  check: "tcp-ping"
  #  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /learning_server_check
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TheHardDiamond's Server Check - 皮肤站坚不可摧
  introTitle: "Welcome to TheHardDiamond's Server monitor website."
  introMessage: This is a sample status page which uses **real-time** data from [CSU-MC Servers](https://www.csu-mc.magicalsheep.cn/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
